### ISSUE TITLE
Multiple objects with one html file

### ISSUE THREAD

**Issue by annapoliswu** [annapoliswu/chemSims#3]
Wanted to separate input part out to one class using one html file, to make it easier to create separate input lines. When creating new elements from the same .html file, the ids and class labels stay the same. So getElementById would create undefined behavior. Using getElementsByClassName[ instanceNumber] to get the specific html objects, not sure if there's a better way?
https://github.com/annapoliswu/chemSims/blob/b1a77555bb2520fbb913cb55a7a675e241803361/src/scripts/objects/inputLine.ts#L7-L30

Tried having a static count inside the class to keep track of numInstances: 
https://github.com/annapoliswu/chemSims/blob/665d3a79dc71c257c86de9f4a2e251f0549f083f/src/scripts/objects/inputLine.ts#L7-L31
Seems to be keeping the correct count, but there were display issues with the scene not moving on and I don't know why. Having the scene keep track of the number of instances rn...

**Comment by acbart** [comment]
I believe the solution is to use `this.form.node` instead of `document`. This limits the search of `getElementsByClassName` to just the children of the created `inputLine`. Since the `getElementsByClassName` still returns a list, we still have to index it; but we just want the first element.

```typescript
        this.label = (<HTMLParagraphElement>this.form.node.getElementsByClassName("label")[0]);
        this.input = (<HTMLInputElement>this.form.node.getElementsByClassName("input")[0]);
        this.submit = (<HTMLInputElement>this.form.node.getElementsByClassName("submit")[0]);
```

Documentation on the [node](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.DOMElement.html#node__anchor) attribute.
